### ISSUE TITLE
stack trace Wicket forge 5.0.1 + Idea: 14.1.1

### ISSUE THREAD

**Issue by jamerlan** [wicketforge/wicketforge#166] opened 2015-04-03 14:49 UTC
Wicket forge 5.0.1
Idea: 14.1.1
I dont know what really caused this:

Invalid range specified: (1,-1); 
java.lang.Throwable
    at com.intellij.openapi.diagnostic.Logger.error(Logger.java:115)
    at com.intellij.openapi.util.TextRange.assertProperRange(TextRange.java:219)
    at com.intellij.openapi.util.TextRange.assertProperRange(TextRange.java:214)
    at com.intellij.openapi.util.TextRange.assertProperRange(TextRange.java:210)
    at com.intellij.openapi.util.TextRange.<init>(TextRange.java:43)
    at com.intellij.openapi.util.TextRange.<init>(TextRange.java:32)
    at wicketforge.psi.references.MarkupWicketIdReference.<init>(MarkupWicketIdReference.java:43)
    at wicketforge.psi.references.MarkupWicketIdReferenceProvider.getReferencesByElement(MarkupWicketIdReferenceProvider.java:41)
    at com.intellij.psi.impl.source.resolve.reference.ReferenceProvidersRegistryImpl.doGetReferencesFromProviders(ReferenceProvidersRegistryImpl.java:124)
    at com.intellij.psi.impl.source.resolve.reference.ReferenceProvidersRegistry.getReferencesFromProviders(ReferenceProvidersRegistry.java:70)
    at com.intellij.psi.impl.source.resolve.reference.ReferenceProvidersRegistry.getReferencesFromProviders(ReferenceProvidersRegistry.java:61)
    at com.intellij.psi.impl.source.xml.XmlAttributeValueImpl.getReferences(XmlAttributeValueImpl.java:104)
    at wicketforge.highlighting.WicketForgeHighlightingPass.hasReference(WicketForgeHighlightingPass.java:121)
    at wicketforge.highlighting.WicketForgeHighlightingPass.access$000(WicketForgeHighlightingPass.java:44)
    at wicketforge.highlighting.WicketForgeHighlightingPass$1.visitXmlAttribute(WicketForgeHighlightingPass.java:70)
    at com.intellij.psi.impl.source.xml.XmlAttributeImpl.accept(XmlAttributeImpl.java:152)
    at com.intellij.psi.impl.source.tree.CompositePsiElement.acceptChildren(CompositePsiElement.java:80)
    at com.intellij.psi.XmlRecursiveElementVisitor.visitElement(XmlRecursiveElementVisitor.java:37)
    at com.intellij.psi.XmlElementVisitor.visitXmlElement(XmlElementVisitor.java:22)
    at com.intellij.psi.XmlElementVisitor.visitXmlTag(XmlElementVisitor.java:54)
    at com.intellij.psi.impl.source.xml.XmlTagImpl.accept(XmlTagImpl.java:1017)
    at com.intellij.psi.impl.source.tree.CompositePsiElement.acceptChildren(CompositePsiElement.java:80)
    at com.intellij.psi.XmlRecursiveElementVisitor.visitElement(XmlRecursiveElementVisitor.java:37)
    at com.intellij.psi.XmlElementVisitor.visitXmlElement(XmlElementVisitor.java:22)
    at com.intellij.psi.XmlElementVisitor.visitXmlTag(XmlElementVisitor.java:54)
    at com.intellij.psi.impl.source.xml.XmlTagImpl.accept(XmlTagImpl.java:1017)
    at com.intellij.psi.impl.source.tree.CompositePsiElement.acceptChildren(CompositePsiElement.java:80)
    at com.intellij.psi.XmlRecursiveElementVisitor.visitElement(XmlRecursiveElementVisitor.java:37)
    at com.intellij.psi.XmlElementVisitor.visitXmlElement(XmlElementVisitor.java:22)
    at com.intellij.psi.XmlElementVisitor.visitXmlTag(XmlElementVisitor.java:54)
    at com.intellij.psi.impl.source.xml.XmlTagImpl.accept(XmlTagImpl.java:1017)
    at com.intellij.psi.impl.source.tree.CompositePsiElement.acceptChildren(CompositePsiElement.java:80)
    at com.intellij.psi.XmlRecursiveElementVisitor.visitElement(XmlRecursiveElementVisitor.java:37)
    at com.intellij.psi.XmlElementVisitor.visitXmlElement(XmlElementVisitor.java:22)
    at com.intellij.psi.XmlElementVisitor.visitXmlTag(XmlElementVisitor.java:54)
    at com.intellij.psi.impl.source.xml.XmlTagImpl.accept(XmlTagImpl.java:1017)
    at com.intellij.psi.impl.source.tree.CompositePsiElement.acceptChildren(CompositePsiElement.java:80)
    at com.intellij.psi.XmlRecursiveElementVisitor.visitElement(XmlRecursiveElementVisitor.java:37)
    at com.intellij.psi.XmlElementVisitor.visitXmlElement(XmlElementVisitor.java:22)
    at com.intellij.psi.XmlElementVisitor.visitXmlTag(XmlElementVisitor.java:54)
    at com.intellij.psi.impl.source.xml.XmlTagImpl.accept(XmlTagImpl.java:1017)
    at com.intellij.psi.impl.source.tree.CompositePsiElement.acceptChildren(CompositePsiElement.java:80)
    at com.intellij.psi.XmlRecursiveElementVisitor.visitElement(XmlRecursiveElementVisitor.java:37)
    at com.intellij.psi.XmlElementVisitor.visitXmlElement(XmlElementVisitor.java:22)
    at com.intellij.psi.XmlElementVisitor.visitXmlDocument(XmlElementVisitor.java:42)
    at com.intellij.psi.impl.source.xml.XmlDocumentImpl.accept(XmlDocumentImpl.java:89)
    at com.intellij.psi.impl.source.tree.SharedImplUtil.acceptChildren(SharedImplUtil.java:196)
    at com.intellij.psi.impl.source.PsiFileImpl.acceptChildren(PsiFileImpl.java:779)
    at com.intellij.psi.XmlRecursiveElementVisitor.visitElement(XmlRecursiveElementVisitor.java:37)
    at com.intellij.psi.PsiElementVisitor.visitFile(PsiElementVisitor.java:34)
    at com.intellij.psi.XmlRecursiveElementVisitor.visitFile(XmlRecursiveElementVisitor.java:55)
    at com.intellij.psi.XmlElementVisitor.visitXmlFile(XmlElementVisitor.java:26)
    at com.intellij.psi.impl.source.xml.XmlFileImpl.accept(XmlFileImpl.java:71)
    at wicketforge.highlighting.WicketForgeHighlightingPass.doCollectInformation(WicketForgeHighlightingPass.java:64)
    at com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:67)
    at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass$1$1.run(PassExecutorService.java:438)
    at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1104)
    at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass$1.run(PassExecutorService.java:429)
    at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:452)
    at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:402)
    at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
    at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.a(PassExecutorService.java:426)
    at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.run(PassExecutorService.java:402)
    at com.intellij.concurrency.JobLauncherImpl$VoidForkJoinTask.exec(JobLauncherImpl.java:202)
    at jsr166e.ForkJoinTask.doExec(ForkJoinTask.java:260)
    at jsr166e.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:858)
    at jsr166e.ForkJoinPool.scan(ForkJoinPool.java:1687)
    at jsr166e.ForkJoinPool.runWorker(ForkJoinPool.java:1642)
    at jsr166e.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:109)

**Comment by minman** [comment] 2015-04-11 07:41
so you cannot reproduce this issue?

**Comment by jamerlan** [comment] 2015-04-11 09:07
No, I can't. If its not clear what was wrong from stack trace - then you can close this bug report. Thank you!

**Comment by jamerlan** [comment] 2015-04-11 09:08
I have a big project. And I don't know what I was doing to have this error.

**Comment by minman** [comment] 2015-04-20 20:16
Well, the MarkupWicketIdReferenceProvider causing this issue shouldn't get called in this case; I just can imagine that it happens during indexing or another long running action. How ever, as workaround I will add a range check so it shouldn't happen again.

**Comment by bamarc** [comment] 2021-08-12 22:13
Closing because half a decade and dozens of IntelliJ releases have passed.

**Closed by bamarc** 2021-08-12 22:13 UTC
